version: '3.7'

services:
  db:
    image: postgres:11.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: 
      context: ./Arthur
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Arthur:/code
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:

